# 公共配置文件模板
spring:
  application:
    name: ${APPLICATION_NAME:service-client}
  # 默认环境配置
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    store-type: ${SESSION_STORE_TYPE:none} # 设置为 'redis' 开启分布式 session
    timeout: ${SESSION_TIMEOUT:2592000} # 30 天过期
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:chengoj}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
  # Redis 配置
  redis:
    database: ${REDIS_DATABASE:1}
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: ${REDIS_TIMEOUT:5000}
    password: ${REDIS_PASSWORD:}
    lettuce:
      pool:
        max-active: ${REDIS_POOL_MAX_ACTIVE:8}
        max-wait: ${REDIS_POOL_MAX_WAIT:10000}
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      config:
        server-addr: ${NACOS_CONFIG_SERVER_ADDR:127.0.0.1:8848}
        file-extension: yml

# 服务器配置
server:
  address: ${SERVER_ADDRESS:0.0.0.0}
  port: ${SERVER_PORT:8105}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api}
    session:
      cookie:
        max-age: ${SESSION_COOKIE_MAX_AGE:2592000}
        path: ${SESSION_COOKIE_PATH:/api}

# MyBatis Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: ${MYBATIS_MAP_UNDERSCORE_TO_CAMEL_CASE:false}
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0)

# 代码沙箱配置
codesandbox:
  type: ${CODESANDBOX_TYPE:remote}
